# CLUSTERISSUER
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    email: {{ .Values.letsencrypt.acme.email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
---
# CERTIFICATE
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-issuer
  namespace: {{ .Release.Namespace }}
spec:
  secretName: acme-crt-secret
  dnsNames:
  - localhost
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reactjs-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: "letsencrypt"
spec:
  tls:
    - hosts:
      - localhost
      secretName: acme-crt-secret
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reactjs-service
            port:
              number: {{ .Values.service.port }}